server:
  port: 8080

logging:
  level:
    com.rogervinas: INFO

spring:
  application:
    name: "stream-demo"
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9094"
      bindings:
        my-producer-out-0:
          destination: "my.topic"
        my-consumer-in-0:
          destination: "my.topic"
          group: "${spring.application.name}"
    function:
      definition: "my-producer;my-consumer"
