server:
  port: 8080

logging:
  level:
    com.rogervinas: INFO

spring:
  application:
    name: "stream-demo"
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
          producer-properties:
            key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
        bindings:
          my-consumer-in-0:
            consumer:
              enable-dlq: true
              dlq-name: "my.topic.errors"
              dlq-partitions: 1
      bindings:
        my-producer-out-0:
          destination: "my.topic"
        my-consumer-in-0:
          destination: "my.topic"
          group: "${spring.application.name}"
          consumer:
            max-attempts: 5
            back-off-initial-interval: 100
            default-retryable: false
            retryable-exceptions:
              com.rogervinas.stream.domain.MyRetryableException: true
    function:
      definition: "my-producer;my-consumer"
